### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by marcello3d**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by marcello3d** [comment]
(signed the CLA)

**Comment by 3den** [comment]
@marcello3d thanks for the PR :) 

Can you make sure to sign the CLA so git does not complain :+1:

**Comment by marcello3d** [comment]
I signed it but not sure how to tell the bot to check again.

**Comment by 3den** [comment]
i am closing this PR because of the bug on the CLA

**Pull request closed without merging**
