### PR TITLE
deprecate simulate native

### PR DESCRIPTION
**Pull request by 3den**
@jakepusateri @mridgway @pbeets https://github.com/yahoo/jsx-test/issues/27

### CODE REVIEW

**Comment by mridgway** [comment]
Looks fine to me. We'll have to find substitutes for the SimulateNative but I don't think jsx-test needs to do that for us.

:+1:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by pbeets** [comment]
:+1:

**Comment by akshayp** [comment]
Thanks @3den! Can you publish this to npm when you have a minute?

**Comment by 3den** [comment]
@akshayp done! I was expecting that to be automatic :P

**Pull request merged**
