### PR TITLE
support react@0.13.x

### PR DESCRIPTION
**Pull request by longlho**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by cesarandreu** [comment]
Awesome! :D

**Comment by 3den** [comment]
:+1:

**Comment by longlho** [comment]
@3den can I get a version bump too pretty please :)

**Comment by 3den** [comment]
sure

**Comment by 3den** [comment]
@longlho the new version is jsx-test@0.4.2

**Comment by longlho** [comment]
:+1:

**Pull request merged**
