### PR TITLE
Revert "require JSX files that can be covered by istanbul."

### PR DESCRIPTION
**Pull request by 3den**
Reverts yahoo/jsx-test#13

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by 3den** [comment]
@stanleyhlng @akshayp I think we should revert now, than rever the revert after the adding coverage to other node versions.

* let me know what you think

**Comment by stanleyhlng** [comment]
@3den which node version do we need to support?

/cc @akshayp

**Comment by 3den** [comment]
@stanleyhlng I think it would be nice to add 0.12 and iojs

**Comment by 3den** [comment]
if you can add that i will close this PR

**Comment by 3den** [comment]
@stanleyhlng published version 0.7.0

**Comment by stanleyhlng** [comment]
@3den sure.

**Pull request closed without merging**
